# Generated by Django 5.1.4 on 2025-05-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='lý do từ chối')),
                ('suggestion', models.TextField(blank=True, null=True, verbose_name='gợi ý chỉnh sửa')),
                ('status', models.CharField(choices=[('DANGGUI', 'Đang gửi'), ('DAGUI', 'Đã gửi'), ('DAXEM', 'Tác giả đã xem')], default='DANGGUI', max_length=20, verbose_name='trạng thái phản hồi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='thời điểm tạo phản hồi')),
            ],
            options={
                'verbose_name': 'Phản hồi bài viết',
                'verbose_name_plural': 'Phản hồi bài viết',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='tiêu đề')),
                ('slug', models.SlugField(blank=True, help_text='Tự động tạo từ tiêu đề nếu để trống.', max_length=255, unique=True)),
                ('content', models.TextField(verbose_name='nội dung')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='ảnh đại diện bài viết')),
                ('status', models.CharField(choices=[('NHAP', 'Nháp'), ('CHODUYET', 'Đang chờ duyệt'), ('DADUYET', 'Đã duyệt'), ('TUCHOI', 'Bị từ chối'), ('DAXUATBAN', 'Đã xuất bản')], default='NHAP', max_length=20, verbose_name='trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='thời điểm cập nhật')),
                ('publish_at', models.DateTimeField(blank=True, help_text="Nếu đặt, bài viết sẽ tự động công khai vào thời điểm này nếu trạng thái là 'Đã duyệt' hoặc 'Đã xuất bản'.", null=True, verbose_name='thời điểm xuất bản dự kiến')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'ordering': ['-publish_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='địa chỉ IP')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='session key')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='thời điểm xem')),
            ],
            options={
                'verbose_name': 'Lượt xem bài viết',
                'verbose_name_plural': 'Lượt xem bài viết',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_tag', models.CharField(max_length=100, unique=True, verbose_name='tên tag')),
                ('slug', models.SlugField(blank=True, help_text='Tự động tạo từ tên tag nếu để trống.', max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
