# Generated by Django 5.1.4 on 2025-05-20 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_received', to=settings.AUTH_USER_MODEL, verbose_name='tác giả nhận'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='editor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['ADMIN', 'BIENTAPVIEN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_given', to=settings.AUTH_USER_MODEL, verbose_name='biên tập viên'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(limit_choices_to={'role': 'TACGIA'}, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='tác giả'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='blog.post', verbose_name='bài viết'),
        ),
        migrations.AddField(
            model_name='postview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='blog.post', verbose_name='bài viết'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.tag', verbose_name='tags'),
        ),
    ]
