# Generated by Django 5.1.4 on 2025-05-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postview',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='user agent'),
        ),
    ]
