# Generated by Django 5.2.1 on 2025-05-22 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postview_user_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_de_tai', models.CharField(max_length=100, unique=True, verbose_name='tên đề tài')),
                ('slug', models.SlugField(blank=True, help_text='Để trống để tự động tạo slug từ tên đề tài.', max_length=120, unique=True, verbose_name='slug')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='mô tả')),
            ],
            options={
                'verbose_name': 'Đề tài',
                'verbose_name_plural': 'Các Đề tài',
                'ordering': ['ten_de_tai'],
            },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['ten_tag'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Các Tags'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='ten_tag',
            field=models.CharField(max_length=50, unique=True, verbose_name='tên tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='đề tài'),
        ),
    ]
